# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='text2',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
